# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# cd ./docs/.vuepress/dist/
# git init
# git add -A
# git config --global user.email "anborong@outlook.com"
# git config --global user.name "AmberAAA"
# git commit -m 'release'
# git push -f git@github.com:AmberAAA/AmberAAA.github.io.git master

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: npm run build
      - name: "push code"
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          env | grep PRIVATE_KEY
          chmod 600  ~/.ssh/id_rsa
          ssh-keyscan anborong.top >> ~/.ssh/known_hosts
          scp -r .// root@anborong.top:~/blog/
