# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# cd ./docs/.vuepress/dist/
# git init
# git add -A
# git config --global user.email "anborong@outlook.com"
# git config --global user.name "AmberAAA"
# git commit -m 'release'
# git push -f git@github.com:AmberAAA/AmberAAA.github.io.git master

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install oss utils
        run: curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      - run: npm run build
      - name: "push code"
        env:
          OSS_ID: ${{ secrets.OSS_ID }}
          OSS_KEY: ${{ secrets.OSS_KEY}}
        run: |
          ossutil rm -e oss-cn-zhangjiakou.aliyuncs.com -i $OSS_ID -k $OSS_KEY -r -f oss://abr-blog/
          ossutil cp -e oss-cn-zhangjiakou.aliyuncs.com -i $OSS_ID -k $OSS_KEY -r -f  ./build/ oss://abr-blog/
